name = "LikelihoodProfiler"
uuid = "934dfcd9-de73-50b3-9b48-36c923fd8802"
keywords = ["package", "management"]
license = "MIT"
desc = "The next-generation Julia package manager."
authors = ["borisov <iv.borissov@gmail.com>", "metelkin <evgeny.metelkin@gmail.com>"]
repo-url = "https://github.com/insysbio/LikelihoodProfiler.jl"
version = "0.3.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
julia = ">=1.1.0"
